AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  admin-automation

  Sample SAM Template for admin-automation

Globals:
  Function:
    Timeout: 9
    MemorySize: 128

    LoggingConfig:
      LogFormat: JSON

Resources:
  AdminAutomationGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: AdminAutomationGateway

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts"

  JsReportLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: jsreport_layer
      Description: jsreport + headless Chromium
      ContentUri:
        Bucket: !Ref ArtifactsBucket
        Key: jsreport/layer.zip
      CompatibleRuntimes:
        - nodejs20.x

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common_layer
      Description: shared helpers
      ContentUri: src/common
      CompatibleRuntimes:
        - python3.12

  OnboardingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: services/onboarding/app.lambda_handler
      Runtime: python3.12
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          GMAIL_APP_PASSWORD: "{{resolve:ssm:/admin-automation/prod/GMAIL_APP_PASSWORD}}"
          JIRA_SERVER: "{{resolve:ssm:/admin-automation/prod/JIRA_SERVER}}"
          JIRA_USER: "{{resolve:ssm:/admin-automation/prod/JIRA_USER}}"
          JIRA_API_TOKEN: "{{resolve:ssm:/admin-automation/prod/JIRA_API_TOKEN}}"
          PRIMARY_GMAIL_SENDER_ADDRESS: "{{resolve:ssm:/admin-automation/prod/PRIMARY_GMAIL_SENDER_ADDRESS}}"
          SECONDARY_GMAIL_SENDER_ADDRESS: "{{resolve:ssm:/admin-automation/prod/SECONDARY_GMAIL_SENDER_ADDRESS}}"
          BUDDY_PROGRAM_VENDOR_ADDRESSES: "{{resolve:ssm:/admin-automation/prod/BUDDY_PROGRAM_VENDOR_ADDRESSES}}"
          COORDINADORA_API: "{{resolve:ssm:/admin-automation/prod/COORDINADORA_API}}"
          COORDINADORA_USER: "{{resolve:ssm:/admin-automation/prod/COORDINADORA_USER}}"
          COORDINADORA_USER_ID: "{{resolve:ssm:/admin-automation/prod/COORDINADORA_USER_ID}}"
          COORDINADORA_PASSWORD: "{{resolve:ssm:/admin-automation/prod/COORDINADORA_PASSWORD}}"
          SLACK_BOT_TOKEN: "{{resolve:ssm:/admin-automation/prod/SLACK_BOT_TOKEN}}"
          SLACK_OB_CHANNEL_ID: "{{resolve:ssm:/admin-automation/prod/SLACK_OB_CHANNEL_ID}}"
      Architectures:
        - x86_64
      Events:
        Endopoint:
          Type: Api
          Properties:
            RestApiId: !Ref AdminAutomationGateway
            Path: /onboarding-automation
            Method: post

  JsReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: src/
      Handler: services/jsreport/index.handler
      Layers:
        - !Ref JsReportLayer
      MemorySize: 1024
      Timeout: 60

  CertificatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: services/certificates/app.lambda_handler
      Runtime: python3.12
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          PRIMARY_GMAIL_SENDER_ADDRESS: "{{resolve:ssm:/admin-automation/prod/PRIMARY_GMAIL_SENDER_ADDRESS}}"
          GMAIL_APP_PASSWORD: "{{resolve:ssm:/admin-automation/prod/GMAIL_APP_PASSWORD}}"
          JIRA_SERVER: "{{resolve:ssm:/admin-automation/prod/JIRA_SERVER}}"
          JIRA_USER: "{{resolve:ssm:/admin-automation/prod/JIRA_USER}}"
          JIRA_API_TOKEN: "{{resolve:ssm:/admin-automation/prod/JIRA_API_TOKEN}}"
          SLACK_BOT_TOKEN: "{{resolve:ssm:/admin-automation/prod/SLACK_BOT_TOKEN}}"
          SLACK_OB_CHANNEL_ID: "{{resolve:ssm:/admin-automation/prod/SLACK_OB_CHANNEL_ID}}"
          BAMBOOHR_SUBDOMAIN: "{{resolve:ssm:/admin-automation/prod/BAMBOOHR_SUBDOMAIN}}"
          BAMBOOHR_API_KEY: "{{resolve:ssm:/admin-automation/prod/BAMBOOHR_API_KEY}}"
          JSREPORT_FUNCTION_NAME: !Ref JsReportFunction
      MemorySize: 1024
      Timeout: 60

      Architectures:
        - x86_64
      Events:
        Endopoint:
          Type: Api
          Properties:
            RestApiId: !Ref AdminAutomationGateway
            Path: /certificates
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref JsReportFunction

  SlackCourierGuideBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: services/slackbot/app.lambda_handler
      Runtime: python3.12
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          SLACK_BOT_TOKEN: "{{resolve:ssm:/admin-automation/prod/SLACK_BOT_TOKEN}}"
      Events:
        Endopoint:
          Type: Api
          Properties:
            Path: /slack-bot
            Method: post
            RestApiId: !Ref AdminAutomationGateway

Outputs:
  ApiUrl:
    Description: Prod endpoint
    Value: !Sub "https://${AdminAutomationGateway}.execute‐api.${AWS::Region}.amazonaws.com/Prod"
